default:
  adapter: mysql2
  database: cats_rescue
  username: meowington
  password: meowguys
  host: localhost
development:
  adapter: mysql2
  database: wdicatsparty
  username: ladycheshire
  password: meowth42
  host: https://db4free.net
  port: 3306
production:
  adapter: mysql2
  database: wdicatsparty
  username: ladycheshire
  password: meowth42
  host: https://db4free.net
  port: 3306
