default:
  adapter: mysql2
  database: cats_rescue
  username: meowington
  password: meowguys
  host: localhost
development:
  adapter: mysql2
  database: wdicatsparty
  username: ladycheshire
  password: meowth42
  host: http://www.db4free.net
production:
  adapter: mysql2
  database: wdicatsparty
  username: ladycheshire
  password: meowth42
  host: http://www.db4free.net
